export * as declarations from "@frontend/ast/nodes/declarations.ts"
export * as statements   from "@frontend/ast/nodes/statements.ts"
export * as expressions  from "@frontend/ast/nodes/expressions.ts"
export * as functions    from "@frontend/ast/nodes/functions.ts"
export * as types        from "@frontend/ast/nodes/types.ts"